export const languages = {
    "arabic": "Арабский",
    "amharic": "Амхарский",
    "english": "Английский",
    "afrikaans": "Африкаанс",
    "albanian": "Албанский",
    "armenian": "Армянский",
    "azerbaijani": "Азербайджанский",
    "bengali": "Бенгальский",
    "belarusian": "Белорусский",
    "burmese": "Бирманский",
    "bulgarian": "Болгарский",
    "bosnian": "Боснийский",
    "catalan": "Каталанский",
    "czech": "Чешский",
    "chinese": "Китайский",
    "danish": "Датский",
    "dari": "Дари",
    "dutch": "Нидерландский",
    "dzongkha": "Дзонг-кэ",
    "estonian": "Эстонский",
    "filipino": "Филиппинский",
    "finnish": "Финский",
    "french": "Французский",
    "georgian": "Грузинский",
    "german": "Немецкий",
    "greek": "Греческий",
    "hebrew": "Иврит",
    "hindi": "Хинди",
    "croatian": "Хорватский",
    "hungarian": "Венгерский",
    "icelandic": "Исландский",
    "indonesian": "Индонезийский",
    "irish": "Ирландский",
    "italian": "Итальянский",
    "japanese": "Японский",
    "kazakh": "Казахский",
    "khmer": "Кхмерский",
    "kinyarwanda": "Киньяруанда",
    "kirundi": "Кирунди",
    "korean": "Корейский",
    "kyrgyz": "Киргизский",
    "lao": "Лаосский",
    "latvian": "Латышский",
    "lithuanian": "Литовский",
    "luxembourgish": "Люксембургский",
    "macedonian": "Македонский",
    "malagasy": "Малагасийский",
    "malay": "Малайский",
    "maltese": "Мальтийский",
    "maori": "Маори",
    "moldovan": "Молдавский",
    "mongolian": "Монгольский",
    "montenegrin": "Черногорский",
    "nepali": "Непальский",
    "norwegian": "Норвежский",
    "pashto": "Пушту",
    "persian": "Персидский",
    "polish": "Польский",
    "portuguese": "Португальский",
    "romanian": "Румынский",
    "russian": "Русский",
    "samoan": "Самоанский",
    "serbian": "Сербский",
    "sinhala": "Сингальский",
    "slovak": "Словацкий",
    "slovene": "Словенский",
    "somali": "Сомалийский",
    "spanish": "Испанский",
    "swahili": "Суахили",
    "swedish": "Шведский",
    "tajik": "Таджикский",
    "tamil": "Тамильский",
    "thai": "Тайский",
    "turkish": "Турецкий",
    "turkmen": "Туркменский",
    "ukrainian": "Украинский",
    "urdu": "Урду",
    "uzbek": "Узбекский",
    "vietnamese": "Вьетнамский",
    "welsh": "Валлийский",
    "berber": "Берберский",
    "quechua": "Кечуа",
    "aymara": "Аймара",
    "guarani": "Гуарани",
    "dhivehi": "Мальдивский",
    "tigrinya": "Тигринья",
    "sesotho": "Сесото",
    "setswana": "Сетсвана",
    "chichewa": "Чева",
    "kurdish": "Курдский",
    "sango": "Санго",
    "tok pisin": "Ток-писин",
    "hiri motu": "Хири-моту",
    "nauruan": "Науруанский",
    "palauan": "Палауский",
    "marshallese": "Маршалльский",
    "kiribati": "Гилбертский",
    "tongan": "Тонганский",
    "fijian": "Фиджийский",
    "bislama": "Бислама",
    "haitian creole": "Гаитянский креольский",
    "tetum": "Тетум",
    "tswana": "Тсвана",
    "swati": "Свати"
};

export const languageLevels = {
    'A1': 'Начальный (A1)',
    'A2': 'Элементарный (A2)',
    'B1': 'Средний (B1)',
    'B2': 'Выше среднего (B2)',
    'C1': 'Продвинутый (C1)',
    'C2': 'В совершенстве (C2)',
    'N': 'Родной',
}